// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    apiUrl: "https://lms-qa-backend.azurewebsites.net/api",
    token: ""
  }
});

export default function() {
  group("Stats", function() {
    postman[Request]({
      name: "Get ICC Standings",
      id: "97c86f7e-1f46-46d7-813f-79081d9a2006",
      method: "GET",
      address:
        "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/iccstanding/team/matchtype/2",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for ICC Standings is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Get ICC Rankings",
      id: "5e3f82b7-2302-49a8-a9a5-09d9297a159b",
      method: "GET",
      address:
        "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/rankings/batsmen?formatType=t20",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for ICC Rankings is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });
  });

  group("Teams", function() {
    postman[Request]({
      name: "Get Teams List",
      id: "a8679ab6-c8e7-4df2-af1e-0a218643ecb6",
      method: "GET",
      address: "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/international",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for Teams is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Get Players",
      id: "5bb2ebf8-2fa0-47e6-ad08-c4f2ef7b5e20",
      method: "GET",
      address: "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/2/players",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for Players is 200", function(){
          pm.response.to.have.status(300);
        });
      }
    });
  });

  group("News List", function() {
    postman[Request]({
      name: "Get News List",
      id: "837b43de-5f5e-4d75-a7a1-5a9a07f400fb",
      method: "GET",
      address: "https://cricbuzz-cricket.p.rapidapi.com/news/v1/index",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for News List is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Get News Details",
      id: "ab095d6f-fd46-472c-9be6-d3c352c54c67",
      method: "GET",
      address: "https://cricbuzz-cricket.p.rapidapi.com/news/v1/detail/122025",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for News Details is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });
  });

  group("Series", function() {
    postman[Request]({
      name: "Get Series List",
      id: "475aad9d-b8c3-4e15-8d64-bda51587ea52",
      method: "GET",
      address:
        "https://cricbuzz-cricket.p.rapidapi.com/series/v1/international",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for Series List is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Get Series List Copy",
      id: "4198cae7-d381-4680-b591-5062282979d4",
      method: "GET",
      address: "https://cricbuzz-cricket.p.rapidapi.com/series/v1/3641",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for Series List is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Get Points Table",
      id: "72653c49-ddce-4d40-9dbe-953aca42c3c4",
      method: "GET",
      address:
        "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/series/3718/points-table",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for Points Table is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "New Request",
      id: "29b511b0-4eac-4b7a-80a8-4bb7d20888f0",
      method: "GET",
      address:
        "https://cricbuzz-cricket.p.rapidapi.com/schedule/v1/international",
      headers: {
        "X-RapidAPI-Key": "fa2859d5a3msh2a46eb1fd89e982p149436jsncb8c4e471491",
        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
      },
      post(response){
        pm.test("Status code for New Request is 200", function(){
          pm.response.to.have.status(200);
        });
      }
    });
  });
}
